#
# Jz4770 Platform Support
#
snd-soc-jz4770-objs := jz4770-pcm.o
snd-soc-jz4770-i2s-objs := jz4770-i2s.o

obj-$(CONFIG_SND_JZ4770_SOC) += snd-soc-jz4770.o
obj-$(CONFIG_SND_JZ4770_SOC_I2S) += snd-soc-jz4770-i2s.o

# JZ4770 Machine Support
snd-soc-gcw0-objs := gcw0.o

obj-$(CONFIG_SND_JZ4770_SOC_GCW0) += snd-soc-gcw0.o
